services:
  tinyproxy-devcontainer:
    image: ai-agents-sandbox/tinyproxy:1.0.0
    environment:
      USER_WHITELIST_DOMAINS: gitlab.com,youtrack.com
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    # user-level overrides can mount additional volumes locally if desired
