services:
  # Core services - always running
  docker-dind:
    image: docker:28-dind
    container_name: docker
    privileged: true  # Required for DinD
    restart: unless-stopped
    ports:
      - "2376:2376"  # TLS Docker daemon
    env_file: .env
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - docker-data:/var/lib/docker
    tmpfs:
      - /run
      - /tmp
    networks:
      - claude-internal

  tinyproxy:
    image: tinyproxy-whitelist:latest
    container_name: tinyproxy
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      - UPSTREAM_SOCKS5=${UPSTREAM_SOCKS5:-}
      - UPSTREAM_HTTP=${UPSTREAM_HTTP:-}
      - UPSTREAM_PROXY_TYPE=${UPSTREAM_PROXY_TYPE:-}
      - UPSTREAM_PROXY_HOST=${UPSTREAM_PROXY_HOST:-}
      - UPSTREAM_PROXY_PORT=${UPSTREAM_PROXY_PORT:-}
    volumes:
      - ./whitelist.txt:/etc/tinyproxy/user-whitelist.txt:ro
      - proxy-logs:/var/log/tinyproxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - claude-internal
      - claude-external

  # Development container - for IDE integration
  # Uncomment or use with docker compose up devcontainer
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-sandbox
    user: claude
    env_file: .env
    volumes:
      - ..:/workspace:cached
      - claude-code-config:/home/claude/.claude
      - claude-code-zshhistory:/home/claude/.zsh_history
      - ${HOME}/.claude:/host/.claude:ro
      - ${HOME}/.claude-docker-certs:/certs/client:ro
      - ${HOME}/.p10k.zsh:/host/.p10k.zsh:ro
    working_dir: /workspace
    command: sleep infinity
    networks:
      - claude-internal
    depends_on:
      - docker-dind
      - tinyproxy

volumes:
  docker-certs-ca:
  docker-certs-client:
  docker-data:
  proxy-logs:
  claude-code-config:
  claude-code-zshhistory:

networks:
  claude-internal:
    name: claude-internal
    driver: bridge
    internal: true  # Critical: blocks direct internet access
  claude-external:
    name: claude-external
    driver: bridge