services:
  tinyproxy-devcontainer:
    image: ai-sandbox/tinyproxy-whitelist:1.0.0
    environment:
      USER_WHITELIST_DOMAINS: gitlab.com,youtrack.com
  
  tinyproxy-dind:
    image: ai-sandbox/tinyproxy-dind:1.0.0
    environment:
      USER_WHITELIST_DOMAINS: hub.docker.com

  devcontainer:
    # Option 1: Use environment variable from .env (RECOMMENDED)
    # This works because PROJECT_DIR is set in .env
    build:
      context: .
      dockerfile: Dockerfile
    
    # Option 2: Use pre-built image (no build needed)
    # image: ai-sandbox/devcontainer:1.0.0