# Devcontainer proxy configuration - ONLY uses tinyproxy-devcontainer
x-devcontainer-proxy-env: &devcontainer-proxy-env
  HTTP_PROXY: ${PROXY_URL:-http://tinyproxy-devcontainer:8888}
  HTTPS_PROXY: ${PROXY_URL:-http://tinyproxy-devcontainer:8888}
  NO_PROXY: ${NO_PROXY:-localhost,127.0.0.1,::1,docker}
  # Lowercase versions for compatibility
  http_proxy: ${PROXY_URL:-http://tinyproxy-devcontainer:8888}
  https_proxy: ${PROXY_URL:-http://tinyproxy-devcontainer:8888}
  no_proxy: ${NO_PROXY:-localhost,127.0.0.1,::1,docker}

services:
  # Docker-in-Docker service
  docker:
    image: docker:28-dind
    privileged: true  # Required for DinD
    restart: unless-stopped
    environment:
      # DinD ONLY uses tinyproxy-dind for registry access - NEVER tinyproxy-devcontainer
      HTTP_PROXY: http://tinyproxy-dind:8888
      HTTPS_PROXY: http://tinyproxy-dind:8888
      NO_PROXY: localhost,127.0.0.1,::1
      http_proxy: http://tinyproxy-dind:8888
      https_proxy: http://tinyproxy-dind:8888
      no_proxy: localhost,127.0.0.1,::1
    volumes:
      # must be added here for successful mounts to interpreter containers inside devcontainer
      - ${PROJECT_DIR:-..}:/workspace
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - docker-data:/var/lib/docker
    tmpfs:
      - /run
      - /tmp
    networks:
      - claude-internal
    depends_on:
      - tinyproxy-dind  # ONLY depends on its own proxy

  # Main proxy for devcontainer - supports upstream proxy
  tinyproxy-devcontainer:
    image: ai-agents-sandbox/tinyproxy:latest
    restart: unless-stopped
    environment:
      # Simplified upstream proxy configuration
      UPSTREAM_PROXY: ${UPSTREAM_PROXY:-}  # Format: socks5://host:port or http://host:port
      NO_UPSTREAM: ${NO_UPSTREAM:-}         # Domains that bypass upstream
      USER_WHITELIST_DOMAINS: ${USER_WHITELIST_DOMAINS:-}  # Comma or space separated list
    volumes:
      - proxy-devcontainer-logs:/var/log/tinyproxy
    extra_hosts:
      - "host.gateway:host-gateway"  # Maps to Docker host for upstream proxy
    networks:
      - claude-internal
      - claude-external

  # Dedicated proxy for Docker-in-Docker - no upstream, direct registry access
  tinyproxy-dind:
    image: ai-agents-sandbox/tinyproxy-dind:latest
    restart: unless-stopped
    environment:
      # No upstream proxy for dind - direct registry access only
      UPSTREAM_PROXY_TYPE: none
      USER_WHITELIST_DOMAINS: ${DIND_WHITELIST_DOMAINS:-}  # Additional registry domains
    volumes:
      - proxy-dind-logs:/var/log/tinyproxy
    networks:
      - claude-internal
      - claude-external

  # Development container
  devcontainer:
    user: claude
    environment:
      <<: *devcontainer-proxy-env
      # Project-specific environment
      PROJECT_NAME: ${PROJECT_NAME:-project}
      WORKSPACE: ${WORKSPACE:-/workspace}
      # Docker-in-Docker client configuration
      # Docker connection is internal network only - no proxy needed
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: "1"
      DOCKER_CERT_PATH: /certs/client
      # JetBrains remote development
      JETBRAINS_REMOTE_RUN: "true"
      # Claude Code configuration
      CLAUDE_CONFIG_DIR: /home/claude/.claude
      NODE_OPTIONS: --max-old-space-size=4096
    volumes:
      # Core volumes
      - ${PROJECT_DIR:-..}:/workspace
      - claude-code-config:/home/claude/.claude
      - docker-certs-client:/certs/client:ro
      
      # User configuration volumes
      - ${HOME}/.ai_agents_sandbox:/host/.ai_agents_sandbox:ro
      - ${HOME}/.p10k.zsh:/host/.p10k.zsh:ro
      - ${HOME}/.ai_agents_sandbox/projects/:/home/claude/.ai_agents_sandbox/projects
      - ${HOME}/.ai_agents_sandbox/notifications:/home/claude/.ai_agents_sandbox/notifications
      
      # Persistent state volumes
      - codex:/home/claude/.codex
      - cache:/home/claude/.cache
      
      # IDE cache for JetBrains
      - jb-cache:/.jbdevcontainer
    ports:
      # OpenAI Codex auth port
      - "${CODEX_PORT:-1455}:1455"
    working_dir: /workspace
    networks:
      - claude-internal
    depends_on:
      - docker  # For Docker CLI access
      - tinyproxy-devcontainer  # ONLY its own proxy, NOT tinyproxy-dind
    # Allow custom command override
    command: ${DEVCONTAINER_COMMAND:-sleep infinity}

volumes:
  docker-certs-ca:
    name: ${PROJECT_NAME:-project}-docker-certs-ca
  docker-certs-client:
    name: ${PROJECT_NAME:-project}-docker-certs-client
  docker-data:
    name: ${PROJECT_NAME:-project}-docker-data
  proxy-devcontainer-logs:
    name: ${PROJECT_NAME:-project}-proxy-devcontainer-logs
  proxy-dind-logs:
    name: ${PROJECT_NAME:-project}-proxy-dind-logs
  claude-code-config:
    name: ${PROJECT_NAME:-project}-claude-code-config
  codex:
    name: ${PROJECT_NAME:-project}-codex
  cache:
    name: ${PROJECT_NAME:-project}-cache
  jb-cache:
    name: ${PROJECT_NAME:-project}-jb-cache

networks:
  claude-internal:
    name: ${PROJECT_NAME:-project}-claude-internal
    driver: bridge
    internal: true  # Critical: blocks direct internet access
  claude-external:
    name: ${PROJECT_NAME:-project}-claude-external
    driver: bridge